// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mstefpauvetioyjeosos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdGVmcGF1dmV0aW95amVvc29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjQ5ODksImV4cCI6MjA2MDY0MDk4OX0.gxQEq2_lyrN09cm59FvXeB8suqLfRHDFhaosyLCvRko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);